# Playbook general, notre point d'entrée

- hosts: all
  become: true
  tags:
    - bootstrap
  roles: 
    - role: bootstrap
      bootstrap_motd: "motd dans le role"


- hosts: webservers
  become: true
  tags:
    - webserver
  roles: 
    - webserver
