# Petit playbook pour créer un web server
---
- hosts: webservers
  become: true
  vars:
    webserver_name:
      RedHat: httpd
      Debian: apache2
  tasks:
  - name: "installation httpd"
    package:
      name: "{{webserver_name[ansible_os_family]}}"
      state: present 
  - name: "start httpd"
    ansible.builtin.service:
      name: "{{webserver_name[ansible_os_family]}}"
      state: started
      enabled: true
  - name: "stop firewall"
    ansible.builtin.service:
      name: firewalld
      state: stopped
    when: ansible_os_family == 'RedHat'
  - name : recup fait sur node3'
    setup:
      filter: ansible_eth0
    delegate_to: "{{item}}"
    delegate_facts: true
    loop: "{{ groups.webservers }}"
    when: inventory_hostname != item
  - name : debug
    debug :
      var: hostvars['node3'].ansible_eth0.ipv4.address
  - name: "Copy index.html"
    ansible.builtin.template:
      src: index.html.j2
      dest: /var/www/html/index.html
      mode: "0644"
  - name: Creation repertoire site
    file:
      state: directory
      path: "/var/www/html/{{item}}"
    loop: "{{ webserver_sites }}"
  - name: "Deploiement site"
    ansible.builtin.copy:
      content: "Ce site est {{item}}"
      dest: "/var/www/html/{{item}}/index.html"
      mode: "0644"
    loop: "{{ webserver_sites }}"


 

